quarkus:
  datasource:
    axon:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default
  hibernate-orm:
    axon:
      dialect: org.hibernate.dialect.H2Dialect
      database:
        generation: drop-and-create
      datasource: axon
      packages: > 
        org.axonframework.eventsourcing.eventstore.jpa, 
        org.axonframework.eventhandling, 
        org.axonframework.eventhandling.deadletter.jpa, 
        org.axonframework.eventsourcing.eventstore
  index-dependency:
    axon-eventsourcing:
      group-id: org.axonframework
      artifact-id: axon-eventsourcing
    axon-messaging:
      group-id: org.axonframework
      artifact-id: axon-messaging